sudo: required
services:
  - docker

before-install:
  - docker build -t mechoshipuhanaga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mechoshipuhanaga/react-test yarn test

after_success:
  - docker build -t mechoshipuhanaga/multi-client ./client
  - docker build -t mechoshipuhanaga/multi-nginx ./nginx
  - docker build -t mechoshipuhanaga/multi-server ./server
  - docker build -t mechoshipuhanaga/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mechoshipuhanaga/multi-client
  - docker push mechoshipuhanaga/multi-nginx
  - docker push mechoshipuhanaga/multi-server
  - docker push mechoshipuhanaga/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-234589310433
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
